"""Shared limits and constants used across the package."""

MAX_FILES_FOR_SYNTHESIS = 150
MAX_FILES_FOR_PATTERNS = 200
MAX_FILES_FOR_DEP_GRAPH = 2000
MAX_FILE_READ_BYTES = 2 * 1024 * 1024

DEFAULT_MAX_OUTPUT_TOKENS = 2000
DEFAULT_MODEL = "claude-sonnet-4-5"

PARSE_WORKERS = 4
